on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: RojerGS/python-black-check@master
      with:
        line-length: '89'
        path: './smiter'
        exclude: '(/*.html|/*.mo|/*.po|/*.png|/*.rst)'
