uses: RojerGS/python-black-check@master
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
with:
  line-length: '81'
  path: '.'
  include: 'apps'
  exclude: '(/*.html|/*.mo|/*.po|/*.png|/*.rst)'
